services:
    api:
        build:
            context: .docker
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - .:/var/www
            - ./database/sqlite/loayalty_api.sqlite:/var/www/database/sqlite/loayalty_api.sqlite
        container_name: loyalty-api
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "8000:8000"
